FROM python:3.10-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpangoft2-1.0-0 \
    libpango1.0-0 \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/run/gunicorn

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ .

COPY scripts/entrypoint.dev.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 8001

ENTRYPOINT ["/entrypoint.sh"]
CMD ["python3", "manage.py", "runserver", "0.0.0.0:8001"]